<?php

namespace ContainerW5iJ7FW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosCkEditor_InstallerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'fos_ck_editor.installer' shared service.
     *
     * @return \FOS\CKEditorBundle\Installer\CKEditorInstaller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/ckeditor-bundle/src/Installer/CKEditorInstaller.php';

        return $container->privates['fos_ck_editor.installer'] = new \FOS\CKEditorBundle\Installer\CKEditorInstaller();
    }
}
