vich_uploader:
    db_driver: orm
    
    # metadata:
    #     type: attribute

    # mappings:
    #     documents_directory:
    #         uri_prefix: '%app.path.images_articles%'
    #         upload_destination: '%kernel.project_dir%/public%app.path.images_articles%'
    #         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #         delete_on_update: false
    #         delete_on_remove: true
            
