<?php

namespace ContainerNLa5dSC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GnEwx5tService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.gnEwx5t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gnEwx5t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.gnEwx5t.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.gnEwx5t": it references class "App\\Entity\\Article" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'markRepository' => ['privates', 'App\\Repository\\MarkRepository', 'getMarkRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'manager' => '?',
            'markRepository' => 'App\\Repository\\MarkRepository',
        ]);
    }
}
