<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2OZ6q4V\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2OZ6q4V/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container2OZ6q4V.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container2OZ6q4V\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container2OZ6q4V\App_KernelProdContainer([
    'container.build_hash' => '2OZ6q4V',
    'container.build_id' => '65311a09',
    'container.build_time' => 1659030138,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2OZ6q4V');
