<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG4FpxuX\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG4FpxuX/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerG4FpxuX.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerG4FpxuX\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerG4FpxuX\App_KernelProdContainer([
    'container.build_hash' => 'G4FpxuX',
    'container.build_id' => 'e2cc9586',
    'container.build_time' => 1659525330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG4FpxuX');
