<?php

namespace ContainerTb55n8R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EWbLAAService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.EWbL_aA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EWbL_aA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailService' => ['privates', 'App\\Service\\MailService', 'getMailServiceService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'mailService' => 'App\\Service\\MailService',
            'manager' => '?',
        ]);
    }
}
