<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW5iJ7FW\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW5iJ7FW/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerW5iJ7FW.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerW5iJ7FW\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerW5iJ7FW\App_KernelTestDebugContainer([
    'container.build_hash' => 'W5iJ7FW',
    'container.build_id' => 'c10c1146',
    'container.build_time' => 1657989890,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW5iJ7FW');
