<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL8XJJTt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL8XJJTt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL8XJJTt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL8XJJTt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL8XJJTt\App_KernelDevDebugContainer([
    'container.build_hash' => 'L8XJJTt',
    'container.build_id' => '9097b3c1',
    'container.build_time' => 1659520383,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL8XJJTt');
